### ISSUE TITLE
Website TimeOuts

### ISSUE THREAD

**Issue by iNeil77** [pfliu-nlp/NLPedia-Pretrain#4]
Is the http://pretrain.nlpedia.ai page still online? I am getting time outs when attempting to access it. 

It was a very accessible and useful resource for prompting methods!
Thanks

**Comment by pfliu-nlp** [comment]
Aha, thanks a lot for reporting this case! I just fixed it!

**Comment by iNeil77** [comment]
Thanks! Works now
